version: "3"

services:
    pharos-control:
        container_name: pharos-control
        # Local build
        #image: localhost/docker-pharos-control
        image: docker.io/radioheadlab/privrepo:v0.0.1.pharosctrl
        ulimits:
          nofile:
            soft: 4096
            hard: 8192
        stop_grace_period: 60s
        network_mode: host
        ports:
          - 9321:9321
        volumes:
          - pharos-config:/app/config
        labels:
          - "diun.enable=true"
          - "docker-volume-backup.stop-during-backup=pharosctrl-svc"
        restart: always

volumes:
    pharos-config:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: '/opt/tplink/PharosCtrl/config'